// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.DAL;

#nullable disable

namespace Users.DAL.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20241021135334_ExtendedPhotoPath")]
    partial class ExtendedPhotoPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Users.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("email");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("nick");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("photo_path");

                    b.HasKey("Id");

                    b.HasIndex("Nick")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
