FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

SHELL ["/bin/bash", "-c"]
ARG UID
RUN if ! [[ "$UID" =~ ^[0-9]+$ ]]; then \
  echo "Error: UID argument must be a number." && exit 1; \
  fi
RUN useradd --uid $UID -m admin; 
USER admin

WORKDIR /app
VOLUME [ "/app" ]

EXPOSE 5000

CMD [ "dotnet", "watch" ]